version: '3'
services: 
  sims-helper:
    restart: always
    build: 
      context: ./node/
      dockerfile: Dockerfile
    container_name: sims-helper
    image: turndai/sims-helper:latest
    ports: 
      - 8080:8080
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    expose:
      - "8080"
    command: "npm start"
    volumes: 
      - ./node/app:/home/node/app
    
  #mongo:
  #  image: mongo
  #  restart: always
  #  environment:
  #    MONGO_INITDB_ROOT_USERNAME: root
  #    MONGO_INITDB_ROOT_PASSWORD: example

  #mongo-express:
  #  image: mongo-express
  #  restart: always
  #  ports:
  #    - 8081:8081
  #  environment:
  #    ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #    ME_CONFIG_MONGODB_ADMINPASSWORD: example
